/**
 * NarrativeCard — displays the LLM-generated evolutionary narrative.
 * Renders markdown output from agent_evo.py.
 */

import { MarkdownText } from '../MarkdownText'

interface Props {
  narrative: string
  geneName: string
  isLoading: boolean
}

export function NarrativeCard({ narrative, geneName, isLoading }: Props) {
  if (isLoading) {
    return (
      <div className="space-y-3 p-4">
        <div className="text-xs text-gray-500 mb-4 flex items-center gap-2">
          <svg className="animate-spin h-3.5 w-3.5 text-blue-400" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          Generating evolutionary narrative…
        </div>
        {[0.9, 1, 0.75, 0.85, 1, 0.7].map((w, i) => (
          <div
            key={i}
            className="h-3 bg-gray-800 rounded animate-pulse"
            style={{ width: `${w * 100}%` }}
          />
        ))}
      </div>
    )
  }

  if (!narrative) {
    return (
      <div className="flex items-center justify-center h-24 text-gray-500 text-sm">
        No narrative available.
      </div>
    )
  }

  return (
    <div className="p-4 space-y-4">
      <div className="flex items-center gap-2 pb-2 border-b border-gray-800">
        <div className="w-2 h-2 rounded-full bg-blue-400" />
        <span className="text-xs text-gray-400 uppercase tracking-wide">
          AI-generated evolutionary narrative · {geneName}
        </span>
      </div>

      <div className="text-sm text-gray-200 leading-relaxed space-y-3 [&_h2]:text-blue-300 [&_h2]:font-semibold [&_h2]:mt-4 [&_h3]:text-blue-200 [&_h3]:font-medium [&_strong]:text-white [&_code]:text-green-400 [&_code]:bg-gray-800 [&_code]:px-1 [&_code]:rounded">
        <MarkdownText>{narrative}</MarkdownText>
      </div>

      <div className="pt-3 border-t border-gray-800 text-xs text-gray-600">
        Narrative generated by Claude using Dollo parsimony domain events and per-species
        structural profiles. Verify domain IDs against Pfam/InterPro databases.
        Divergence times from TimeTree (Kumar et al. 2022).
      </div>
    </div>
  )
}
